project:
  type: website
  resources:
    - site_images/**
format:
  html:
    theme: quarto
    light: cosmo
    dark: darkly
    css: styles.css
    toc: true

website:
  title: "Max Larner"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/dissertation/dissertation.qmd
        text: "Dissertation"
      - href: projects/project_list.qmd
        text: Projects
      - href: about.qmd
        text: About Me




